events {}

http {

    upstream users {
        server users-service:8081;
    }

    upstream restaurants {
        server restaurant-service:8082;
    }

    upstream bookings {
        server bookings-service:8083;
    }

    upstream reviews {
        server reviews-service:8084;
    }

    server {
        listen 80;

        # API
        location /users/ {
            proxy_pass http://users/;
        }

        location /restaurants/ {
            proxy_pass http://restaurants/;
        }

        location /bookings/ {
            proxy_pass http://bookings/;
        }

        location /reviews/ {
            proxy_pass http://reviews/;
        }

        # Swagger

        location /users/api-docs/ {
            proxy_pass http://users/api-docs/;
        }

        location /restaurants/api-docs/ {
            proxy_pass http://restaurants/api-docs/;
        }

        location /bookings/api-docs/ {
            proxy_pass http://bookings/api-docs/;
        }

        location /reviews/api-docs/ {
            proxy_pass http://reviews/api-docs/;
        }

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
