server {
    listen 80;
    server_name 158.160.224.131;

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api-docs/users {
        proxy_pass http://localhost:3001/api-docs;
        proxy_set_header Host $host;
    }

    location /api-docs/estates {
        proxy_pass http://localhost:3002/api-docs;
        proxy_set_header Host $host;
    }

    location /api-docs/deals {
        proxy_pass http://localhost:3003/api-docs;
        proxy_set_header Host $host;
    }

    location /api-docs/messaging {
        proxy_pass http://localhost:3004/api-docs;
        proxy_set_header Host $host;
    }

    location /health {
        proxy_pass http://localhost:3000/health;
        proxy_set_header Host $host;
    }
}